# Generated by Django 3.0.5 on 2020-06-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
